services:
  ub:
    image: ubillize
    build:
      context: .
      dockerfile: apps/ub/Dockerfile
    env_file: ".env.docker"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - ubillize
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    env_file: ".env.docker"
    networks:
      - ubillize
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_CONNECTIONS=true
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  taskrun:
    image: ubillize-taskrun
    build:
      context: .
      dockerfile: apps/taskrun/Dockerfile
    env_file: ".env.docker"
    restart: always
    networks:
      - ubillize
    depends_on:
      db:
        condition: service_healthy
    
volumes:
  db-data:

networks:
  ubillize:
    driver: bridge